import java.util.Scanner;
public class exception
{
		public static void main(String args[])
		{
			int a,b,result;
			Scanner sc=new Scanner(System.in);
			System.out.println("enter two integers");
			a=sc.nextInt();
			b=sc.nextInt();
			try
			{
				result=a/b;
				System.out.println("result"+result);
			}
				catch(ArithmeticException e)
				{
					System.out.println("error caught:division by zero");
				}
			}
		